### ISSUE TITLE
This project is no longer needed

### ISSUE THREAD

**Issue by paternal** [jluttine/tikz-in-readthedocs#1]
Some times ago, I made some improvements to sphinxcontrib-tikz, so that it can be run on readthedocs. It does work: https://sphinxcontrib-tikz.readthedocs.io

Unrelated: once philexander has merged the [pending pull-requests](https://bitbucket.org/philexander/tikz/pull-requests/)  (or once you decide that he takes too much time to address them), I think it might be a good idea to publish a new version to pypi (as I think *you* are the pypi maintener of sphinxcontrib-tikz).

Regards,
Louis

**Comment by jluttine** [comment]
Thanks for the info. I'll add a note in README.
